apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v1wz6td3s-go
  janus-idp.io/tekton: v1wz6td3s-go
  backstage.io/kubernetes-id: v1wz6td3s-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v1wz6td3s-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
